name: Rainix CI
on: [push]

concurrency:
  group: ${{ github.ref }}-rainix
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rainix:
    strategy:
      matrix:
        task: [
          rainix-rs-test,
          rainix-rs-artifacts,
          rainix-rs-static,
        ]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Run ${{ matrix.task }}
        run: nix develop -c ${{ matrix.task }}
        working-directory: core

